"""Single-use, time-bound tokens that authorise a password reset.

Why a dedicated table (and not a column on ``users``)
=====================================================

The reset link is a **bearer credential** for one specific operation
("change this user's password without their old one"). Treating it as
a row keeps three properties cheap:

* **Single-use** — flipping ``used_at`` from NULL to ``now()`` is an
  atomic UPDATE we can serialise on. A column on ``users`` would
  require either a separate boolean (more state) or trusting the
  ``expires_at`` to also race-protect, which it doesn't.
* **Multiple outstanding requests** — if a user clicks "Passwort
  vergessen" twice in 30s, both emails should work *until either is
  used*; we don't want the second click to silently invalidate the
  first email already on its way to the inbox. A row per request
  models this naturally.
* **Audit trail** — the row is the evidence that a reset happened.
  Even after the token is used, the row stays around (we don't delete
  it) and the ``used_at`` timestamp is the receipt. The DSGVO
  retention sweep (DS-2 / v23.3) will GC these eventually, but only
  long after they're useful evidence.

Storage model
=============

We persist a SHA-256 hash of the token, never the plaintext. The
plaintext is generated by ``secrets.token_urlsafe(32)`` (256 bits of
entropy), embedded in the email link, and discarded server-side after
the email send. SHA-256 — not bcrypt — for the same reason as
``ApiKey.key_hash``: the entropy is in the token, not in a low-entropy
password, so a fast verify is the right tool.

DSGVO note
==========

``user_id`` cascade-deletes when the user does — Art. 17 erasure
must take the reset history with it. The audit-log entry for
``password_reset_completed`` already lives in a separate table with
its own retention policy (Art. 32 evidence trail).
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


def _utcnow_aware() -> datetime:
    """tz-aware UTC ``now`` for column defaults.

    Most other models in the codebase use a naive ``datetime.utcnow``
    default, which works on Postgres ``TIMESTAMPTZ`` columns
    (asyncpg interprets a naive value as UTC) but causes lexicographic
    string-comparison surprises on SQLite (the test harness). Here
    we default to an *aware* timestamp so the rate-limit query
    (``created_at >= window_start`` with ``window_start`` aware) is
    apples-to-apples regardless of dialect.
    """
    return datetime.now(timezone.utc)


class PasswordResetToken(Base):
    __tablename__ = "password_reset_tokens"

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # SHA-256 hex of the full URL-safe token (64 chars, fixed). We
    # never store the plaintext — verification re-hashes the incoming
    # token and compares. Indexed so the verify path is O(log n).
    token_hash: Mapped[str] = mapped_column(
        String(64), nullable=False, unique=True, index=True
    )
    # 1 hour after creation. Verify rejects when ``now() >= expires_at``.
    # The exact value is set by the service layer so tests can dial it.
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    # NULL until the token is redeemed. After redemption the row stays
    # around as audit evidence; the next verify call sees ``used_at``
    # is set and rejects.
    used_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow_aware, nullable=False
    )
